extends:
  - "plugin:astro/recommended"
  - "prettier"

overrides:
  - files: ["*.ts"]
    parser: "@typescript-eslint/parser"
  - files: ["*.astro"]
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions: [".astro"]
